plugin: amazon.aws.aws_ec2

regions:
  - us-east-1

filters:
  tag:Name: JenkinsServer
  instance-state-name: running

hostnames:
  - public-dns-name

compose:
  ansible_host: public_dns_name
  ansible_user: ubuntu
  ansible_ssh_private_key_file: ~/.ssh/id_rsa

